Modified XQilla to compile against Xerces-C 3.0 beta.
Added pre-processing directives to allow continue to allow compliation
against previous versions of Xerces-C.

Added pre-processing directived to allow compilation against unpatched
versions of Xercec-C 2.8.

--HG--
branch : xqilla

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -843,6 +843,8 @@ am__untar
 xerces_include
 xerces_include_dir
 xerces_lib
+BUILD_DOM_SAMPLES_TRUE
+BUILD_DOM_SAMPLES_FALSE
 CXX
 CXXFLAGS
 LDFLAGS
@@ -2645,8 +2647,6 @@ else
 fi
 
 # Check Xerces library name
-
-
 { echo "$as_me:$LINENO: checking if --with-xerces=DIR option specified" >&5
 echo $ECHO_N "checking if --with-xerces=DIR option specified... $ECHO_C" >&6; }
 
@@ -2662,6 +2662,7 @@ echo "${ECHO_T}$with_xerces" >&6; }
 if test "$with_xerces" = "no"; then
         with_xerces="/usr/local"
 fi
+xerces3="no"
 if test `ls $with_xerces/lib/libxerces-c.*2[6-8].* 2>/dev/null | wc -l` -gt 0 ; then
         { echo "$as_me:$LINENO: checking for Xerces C++ version from source tree" >&5
 echo $ECHO_N "checking for Xerces C++ version from source tree... $ECHO_C" >&6; }
@@ -2680,16 +2681,13 @@ echo "${ECHO_T}$xerces_version" >&6; }
         xerces_lib="$with_xerces/lib"
         xerces_include_dir="$with_xerces/src"
         xerces_include="-I$with_xerces/src"
-elif test `ls $with_xerces/obj/libxerces-c.* 2>/dev/null | wc -l` -gt 0 ; then
+elif test `ls $with_xerces/src/libxerces-c.* 2>/dev/null | wc -l` -gt 0 ; then
         { echo "$as_me:$LINENO: checking for Xerces C++ version from source tree" >&5
 echo $ECHO_N "checking for Xerces C++ version from source tree... $ECHO_C" >&6; }
         { echo "$as_me:$LINENO: result: 3.0+" >&5
 echo "${ECHO_T}3.0+" >&6; }
-        cat >>confdefs.h <<\_ACEOF
-#define HAVE_XERCES3 1
-_ACEOF
-
-        xerces_lib="$with_xerces/lib"
+        xerces3="yes"
+        xerces_lib="$with_xerces/src"
 
         if test `ls $with_xerces/src/xercesc/util/PlatformUtils.hpp 2>/dev/null | wc -l` -gt 0 ; then
            xerces_include_dir="$with_xerces/src"
@@ -2710,6 +2708,16 @@ echo "$as_me: error: The Xerces-C source is required to build XQilla.  $with_xer
 fi
 
 
+
+
+# The DOM samples only build against Xerces-C 3.0 or newer
+ if test "$xerces3" = "yes"; then
+  BUILD_DOM_SAMPLES_TRUE=
+  BUILD_DOM_SAMPLES_FALSE='#'
+else
+  BUILD_DOM_SAMPLES_TRUE='#'
+  BUILD_DOM_SAMPLES_FALSE=
+fi
 
 
 # Check for the BinInputStream::getContentType() method
@@ -3560,9 +3568,8 @@ then
 _ACEOF
 
 else
-        { { echo "$as_me:$LINENO: error: The Xerces-C source code must be patched with the content type patch: xqilla/src/xercesc_content_type.patch" >&5
-echo "$as_me: error: The Xerces-C source code must be patched with the content type patch: xqilla/src/xercesc_content_type.patch" >&2;}
-   { (exit 1); exit 1; }; }
+        { echo "$as_me:$LINENO: WARNING: XQilla will build with reduced functionality. To change this, either use Xerces-C 3.0 or apply xqilla/src/xercesc_content_type.patch to Xerces-C 2.8." >&5
+echo "$as_me: WARNING: XQilla will build with reduced functionality. To change this, either use Xerces-C 3.0 or apply xqilla/src/xercesc_content_type.patch to Xerces-C 2.8." >&2;}
 fi
 
 # Check for the RegularExpression::allMatches() method
@@ -3635,9 +3642,8 @@ then
 _ACEOF
 
 else
-        { { echo "$as_me:$LINENO: error: The Xerces-C source code must be patched with the regex patch: xqilla/src/xercesc_regex.patch" >&5
-echo "$as_me: error: The Xerces-C source code must be patched with the regex patch: xqilla/src/xercesc_regex.patch" >&2;}
-   { (exit 1); exit 1; }; }
+        { echo "$as_me:$LINENO: WARNING: XQilla will build with reduced functionality. To change this, either use Xerces-C 3.0 or apply xqilla/src/xercesc_regex.patch to Xerces-C 2.8." >&5
+echo "$as_me: WARNING: XQilla will build with reduced functionality. To change this, either use Xerces-C 3.0 or apply xqilla/src/xercesc_regex.patch to Xerces-C 2.8." >&2;}
 fi
 
 
@@ -5743,7 +5749,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5746 "configure"' > conftest.$ac_ext
+  echo '#line 5752 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8322,11 +8328,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8325: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8331: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8329: \$? = $ac_status" >&5
+   echo "$as_me:8335: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8612,11 +8618,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8615: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8621: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8619: \$? = $ac_status" >&5
+   echo "$as_me:8625: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8716,11 +8722,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8719: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8725: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8723: \$? = $ac_status" >&5
+   echo "$as_me:8729: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11093,7 +11099,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11096 "configure"
+#line 11102 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11193,7 +11199,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11196 "configure"
+#line 11202 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13594,11 +13600,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13597: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13603: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13601: \$? = $ac_status" >&5
+   echo "$as_me:13607: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13698,11 +13704,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13701: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13707: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13705: \$? = $ac_status" >&5
+   echo "$as_me:13711: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15296,11 +15302,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15299: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15305: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15303: \$? = $ac_status" >&5
+   echo "$as_me:15309: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15400,11 +15406,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15403: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15409: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15407: \$? = $ac_status" >&5
+   echo "$as_me:15413: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17620,11 +17626,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17623: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17629: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17627: \$? = $ac_status" >&5
+   echo "$as_me:17633: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17910,11 +17916,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17913: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17919: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17917: \$? = $ac_status" >&5
+   echo "$as_me:17923: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18014,11 +18020,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18017: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18023: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18021: \$? = $ac_status" >&5
+   echo "$as_me:18027: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21406,11 +21412,14 @@ fi
 { echo "$as_me:$LINENO: checking unicode support in flex" >&5
 echo $ECHO_N "checking unicode support in flex... $ECHO_C" >&6; }
 flex --help | grep "\-U" > /dev/null
-if test "$?" -eq "0"
-	then { echo "$as_me:$LINENO: result: found" >&5
+if test "$?" -eq "0"; then
+	{ echo "$as_me:$LINENO: result: found" >&5
 echo "${ECHO_T}found" >&6; }
-        else { echo "$as_me:$LINENO: WARNING: not found. XQilla requires a version of flex supporting the -U (16-bit unicode) flag if you need to rebuild the lexer." >&5
-echo "$as_me: WARNING: not found. XQilla requires a version of flex supporting the -U (16-bit unicode) flag if you need to rebuild the lexer." >&2;}
+else
+	{ echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6; }
+  { echo "$as_me:$LINENO: WARNING: XQilla requires a version of flex supporting the -U (16-bit unicode) flag if you need to rebuild the lexer." >&5
+echo "$as_me: WARNING: XQilla requires a version of flex supporting the -U (16-bit unicode) flag if you need to rebuild the lexer." >&2;}
 fi
 
 # Set up extra compiler flags for GCC
@@ -23703,6 +23712,13 @@ LIBOBJS=$ac_libobjs
 LTLIBOBJS=$ac_ltlibobjs
 
 
+if test -z "${BUILD_DOM_SAMPLES_TRUE}" && test -z "${BUILD_DOM_SAMPLES_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_DOM_SAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_DOM_SAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -24338,6 +24354,8 @@ am__untar!$am__untar$ac_delim
 xerces_include!$xerces_include$ac_delim
 xerces_include_dir!$xerces_include_dir$ac_delim
 xerces_lib!$xerces_lib$ac_delim
+BUILD_DOM_SAMPLES_TRUE!$BUILD_DOM_SAMPLES_TRUE$ac_delim
+BUILD_DOM_SAMPLES_FALSE!$BUILD_DOM_SAMPLES_FALSE$ac_delim
 CXX!$CXX$ac_delim
 CXXFLAGS!$CXXFLAGS$ac_delim
 LDFLAGS!$LDFLAGS$ac_delim
@@ -24359,8 +24377,6 @@ faxpp_lib!$faxpp_lib$ac_delim
 faxpp_library!$faxpp_library$ac_delim
 tidy_include!$tidy_include$ac_delim
 tidy_lib!$tidy_lib$ac_delim
-tidy_library!$tidy_library$ac_delim
-CC!$CC$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -24402,6 +24418,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+tidy_library!$tidy_library$ac_delim
+CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
 ac_ct_CC!$ac_ct_CC$ac_delim
 CCDEPMODE!$CCDEPMODE$ac_delim
@@ -24432,7 +24450,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 28; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 30; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
