Modified configure.in to be able to check for Xerces 3.0.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -841,6 +841,7 @@ AMTAR
 am__tar
 am__untar
 xerces_include
+xerces_include_dir
 xerces_lib
 CXX
 CXXFLAGS
@@ -2640,6 +2641,8 @@ else
 fi
 
 # Check Xerces library name
+
+
 { echo "$as_me:$LINENO: checking if --with-xerces=DIR option specified" >&5
 echo $ECHO_N "checking if --with-xerces=DIR option specified... $ECHO_C" >&6; }
 
@@ -2662,8 +2665,8 @@ echo $ECHO_N "checking for Xerces C++ version from source tree... $ECHO_C" >&6; 
         { echo "$as_me:$LINENO: result: $xerces_version" >&5
 echo "${ECHO_T}$xerces_version" >&6; }
         xerces_lib="$with_xerces/lib"
-        xerces_include="$with_xerces/src"
-        xerces_library="xerces-c"
+        xerces_include_dir="$with_xerces/src"
+        xerces_include="-I$with_xerces/src"
 elif test `ls $with_xerces/lib/libxerces-c*2[6-8].* 2>/dev/null | wc -l` -gt 0 ; then
         { echo "$as_me:$LINENO: checking for Xerces C++ version from source tree" >&5
 echo $ECHO_N "checking for Xerces C++ version from source tree... $ECHO_C" >&6; }
@@ -2671,8 +2674,31 @@ echo $ECHO_N "checking for Xerces C++ version from source tree... $ECHO_C" >&6; 
         { echo "$as_me:$LINENO: result: $xerces_version" >&5
 echo "${ECHO_T}$xerces_version" >&6; }
         xerces_lib="$with_xerces/lib"
-        xerces_include="$with_xerces/src"
-        xerces_library="xerces-c"
+        xerces_include_dir="$with_xerces/src"
+        xerces_include="-I$with_xerces/src"
+elif test `ls $with_xerces/obj/libxerces-c.* 2>/dev/null | wc -l` -gt 0 ; then
+        { echo "$as_me:$LINENO: checking for Xerces C++ version from source tree" >&5
+echo $ECHO_N "checking for Xerces C++ version from source tree... $ECHO_C" >&6; }
+        { echo "$as_me:$LINENO: result: 3.0+" >&5
+echo "${ECHO_T}3.0+" >&6; }
+        cat >>confdefs.h <<\_ACEOF
+#define HAVE_XERCES3 1
+_ACEOF
+
+        xerces_lib="$with_xerces/lib"
+
+        if test `ls $with_xerces/src/xercesc/util/PlatformUtils.hpp 2>/dev/null | wc -l` -gt 0 ; then
+           xerces_include_dir="$with_xerces/src"
+           xerces_include="-I$with_xerces/src"
+        elif test `ls $with_xerces/../src/xercesc/util/PlatformUtils.hpp 2>/dev/null | wc -l` -gt 0 ; then
+           xerces_include_dir="$with_xerces/../src"
+           xerces_include="-I$with_xerces/../src -I$with_xerces/src"
+        else
+           xerces_include_dir="$with_xerces/src"
+           xerces_include="-I$with_xerces/src"
+           { echo "$as_me:$LINENO: WARNING: Cannot find the Xerces-C source directory - you will have to manually configure $xerces_include." >&5
+echo "$as_me: WARNING: Cannot find the Xerces-C source directory - you will have to manually configure $xerces_include." >&2;}
+        fi
 else
         { { echo "$as_me:$LINENO: error: The Xerces-C source is required to build XQilla.  $with_xerces is not a valid, compiled source tree for Xerces-C.  You must specify the path where Xerces is installed with --with-xerces." >&5
 echo "$as_me: error: The Xerces-C source is required to build XQilla.  $with_xerces is not a valid, compiled source tree for Xerces-C.  You must specify the path where Xerces is installed with --with-xerces." >&2;}
@@ -2681,11 +2707,12 @@ fi
 
 
 
+
 # Check for the BinInputStream::getContentType() method
 
 
 CPPFLAGS_BKUP="$CPPFLAGS"
-CPPFLAGS="$CPPFLAGS -I$xerces_include"
+CPPFLAGS="$CPPFLAGS $xerces_include"
 ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -3538,7 +3565,7 @@ fi
 
 
 CPPFLAGS_BKUP="$CPPFLAGS"
-CPPFLAGS="$CPPFLAGS -I$xerces_include"
+CPPFLAGS="$CPPFLAGS $xerces_include"
 ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -5700,7 +5727,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5703 "configure"' > conftest.$ac_ext
+  echo '#line 5730 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7953,11 +7980,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7956: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7983: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7960: \$? = $ac_status" >&5
+   echo "$as_me:7987: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8221,11 +8248,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8224: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8251: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8228: \$? = $ac_status" >&5
+   echo "$as_me:8255: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8325,11 +8352,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8328: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8355: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8332: \$? = $ac_status" >&5
+   echo "$as_me:8359: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10622,7 +10649,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10625 "configure"
+#line 10652 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10722,7 +10749,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10725 "configure"
+#line 10752 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13058,11 +13085,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13061: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13088: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13065: \$? = $ac_status" >&5
+   echo "$as_me:13092: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13162,11 +13189,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13165: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13192: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13169: \$? = $ac_status" >&5
+   echo "$as_me:13196: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14723,11 +14750,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14726: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14753: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14730: \$? = $ac_status" >&5
+   echo "$as_me:14757: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14827,11 +14854,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14830: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14857: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14834: \$? = $ac_status" >&5
+   echo "$as_me:14861: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17014,11 +17041,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17017: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17044: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17021: \$? = $ac_status" >&5
+   echo "$as_me:17048: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17282,11 +17309,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17285: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17312: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17289: \$? = $ac_status" >&5
+   echo "$as_me:17316: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17386,11 +17413,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17389: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17416: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17393: \$? = $ac_status" >&5
+   echo "$as_me:17420: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -24129,6 +24156,7 @@ AMTAR!$AMTAR$ac_delim
 am__tar!$am__tar$ac_delim
 am__untar!$am__untar$ac_delim
 xerces_include!$xerces_include$ac_delim
+xerces_include_dir!$xerces_include_dir$ac_delim
 xerces_lib!$xerces_lib$ac_delim
 CXX!$CXX$ac_delim
 CXXFLAGS!$CXXFLAGS$ac_delim
@@ -24153,7 +24181,6 @@ tidy_include!$tidy_include$ac_delim
 tidy_lib!$tidy_lib$ac_delim
 tidy_library!$tidy_library$ac_delim
 CC!$CC$ac_delim
-CFLAGS!$CFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -24195,6 +24222,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+CFLAGS!$CFLAGS$ac_delim
 ac_ct_CC!$ac_ct_CC$ac_delim
 CCDEPMODE!$CCDEPMODE$ac_delim
 am__fastdepCC_TRUE!$am__fastdepCC_TRUE$ac_delim
@@ -24221,7 +24249,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 24; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 25; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
