Implemented DebugListener, a debugging/profiling API. Debugging annotations are added to the query after optimisation by the DebugHookDecorator class.
Implemented InteractiveDebugger, an interactive query debugging class
which can be invoked by specifying a "-d" option to the command line
tool.

Simplified genprojects.template removing the need for sed processing,
and renaming it as genprojects.xq. Added gensrcfiles.xq to generate
the srcfiles.in file from the xqilla.template.xml file.

Exported the QueryPathTreeGenerator class under Windows.

diff --git a/wintools/s_projects b/wintools/s_projects
--- a/wintools/s_projects
+++ b/wintools/s_projects
@@ -10,9 +10,6 @@ PROJECTS=xqilla.projects
 # xquery script template
 TEMPLATE=genproject.template
 
-# temporary script, post-sed-replacement
-TEMP_SCRIPT=genproject.script
-
 # xml document input template
 CONFIG_INPUT=xqilla.template.xml
 
@@ -22,28 +19,22 @@ CONFIG_OUTPUT=xqilla.xml
 # substitute some variables in the XML document template
 sed -f lib_paths.sed < $CONFIG_INPUT > $CONFIG_OUTPUT
 
-# for each project/destination, substitute 2 variables in the XQuery script, then run it
+# find the xqilla command line tool
+XQILLA=`which xqilla`
+if [ ! -x "$XQILLA" ]; then
+    XQILLA="../xqilla"
+fi
+if [ ! -x "$XQILLA" ]; then
+    XQILLA="../build/xqilla"
+fi
+if [ ! -x "$XQILLA" ]; then
+    echo "XQilla executable not found. Maybe you need to add it to the path?"
+    exit 1
+fi
+echo XQILLA = $XQILLA
 
-for v in VC7.1 VC8
-do
-    PROJECT_OUTPUT_DIR=../Win32Projects/$v
+# generate the VC7.1 and VC8 project files
+$XQILLA -u genproject.xq -v projectFile "$CONFIG_OUTPUT" -v outputPath "../Win32Projects"
 
-    if [ $v = "VC7.1" ]; then
-	VERSION="7.10"
-    else
-	VERSION="8.00"
-    fi
-
-    for i in `cat $PROJECTS`
-    do
-	sed -e "s!@PROJECT_NAME@!$i!g" -e "s!@PROJECT_INPUT@!$CONFIG_OUTPUT!g" -e"s!@VISUAL_STUDIO_VERSION@!$VERSION!g" < $TEMPLATE > $TEMP_SCRIPT
-	TMP=$PROJECT_OUTPUT_DIR/$i.tmp.vcproj
-	TARG=$PROJECT_OUTPUT_DIR/$i.vcproj
-	xqilla -o $TMP $TEMP_SCRIPT
-	rm -f $TEMP_SCRIPT
-	cmp $TMP $TARG > /dev/null 2>&1 ||
-	(echo "Building $TARG" && rm -f $TARG &&
-	    cp $TMP $TARG && chmod 664 $TARG)
-	rm -f $TMP
-    done
-done
+# generate srcfiles.in, which gets used to create VC6 project files
+$XQILLA gensrcfiles.xq -v projectFile "$CONFIG_OUTPUT" -o srcfiles.in
